# X_TILT_START = -2
X_TILT_START = -1
X_TILT_STOP = 3.7

Y_TILT_START = -2
Y_TILT_STOP = 2

REAL_DATA_COLLECTION_STEP = 0.01
REAL_DATA_COLLECTION_DELAY = 0.1


INFERENCE_MODEL_FILE_NAME = "tuning_512_real_lmdb_512batch_002srate_0001lr15eploop_lmdb_best_model.pth"
INFERENCE_MODEL_TYPE = "WideConv"

TRAINING_IMAGE_RESOLUTION = (512, 512)

LMDB_USE_COMPRESSION = False
